require_relative 'resources/messages'
require_relative 'resources/powerpacks'
require_relative 'resources/accounts'
require_relative 'resources/applications'
require_relative 'resources/recordings'
require_relative 'resources/pricings'
require_relative 'resources/numbers'
require_relative 'resources/conferences'
require_relative 'resources/calls'
require_relative 'resources/token'
require_relative 'resources/endpoints'
require_relative 'resources/addresses'
require_relative 'resources/identities'
require_relative 'resources/phlos'
require_relative 'resources/nodes'
require_relative 'resources/phlo_member'
require_relative 'resources/call_feedback'
require_relative 'resources/media'
require_relative 'resources/brand'
require_relative 'resources/brand_usecases'
require_relative 'resources/campaign'
require_relative 'resources/profile'
require_relative 'resources/lookup'
require_relative 'resources/regulatory_compliance'
require_relative 'resources/multipartycalls'

module Plivo
  module Resources
  end
end
